import "../styles/globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import Header from "@/components/header";
import Footer from "@/components/footer";

interface RootLayoutProps {
  children: ReactNode; // Annotate children with ReactNode type
 
}
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Jasmine Homex",
  description: "Generated by create next app",
};


export default async function RootLayout({children}: RootLayoutProps) {

  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  );
}